### ISSUE TITLE
_DEV_is not defined

### ISSUE THREAD

**Issue by uncleRX** [Durgaprasad-Budhwani/react-native-busy-indicator#8]
hello, i'm using   react-native-busy-indicator.
but i it can't work in my workPlace!

![simulator screen shot 2016 9 5 11 01 34](https://cloud.githubusercontent.com/assets/16251490/18236417/2ec533de-7358-11e6-9b86-295ea681135e.png)

how  to fix it!

**Comment by RealOrangeOne** [comment]
I'm not exactly sure what's causing that, as we arent using __ dev __. What version of react-native are you using?

**Comment by uncleRX** [comment]
i use the React-Native 0.30.0

**Comment by RealOrangeOne** [comment]
hhmmm, I fear this is not a problem with our library, as I can't see `__dev__` anywhere in index. Are you using the most up-to-date version of this library?

**Comment by RealOrangeOne** [comment]
Likely due to outdated version. Variable isnt in our code. Closing
